const $=id=>document.getElementById(id);
const API_BASE=window.VALOHUB_API_URL||'http://localhost:3000';

/* Recherche joueur */
const playerSearch=$('playerSearch');
if(playerSearch){playerSearch.addEventListener('submit',async e=>{e.preventDefault();const v=$('riotId').value.trim(),r=document.querySelector('input[name="region"]:checked')?.value||'EUW';const msg=$('searchMessage'),result=$('playerResult');if(!v||!v.includes('#')){msg.textContent='Entre un Riot ID au format Pseudo#TAG.';result.hidden=true;return}msg.textContent='Recherche en cours...';try{const res=await fetch(`${API_BASE}/api/player?riotId=${encodeURIComponent(v)}&region=${encodeURIComponent(r)}`);if(!res.ok)throw new Error('Joueur introuvable');const data=await res.json();$('resultName').textContent=data.gameName&&data.tagLine?`${data.gameName}#${data.tagLine}`:v;$('resultRegion').textContent=`${r} • API RIOT`;$('apiGameName').textContent=data.gameName||'—';$('apiTagLine').textContent=data.tagLine||'—';$('apiRegion').textContent=r;$('apiMatches').textContent=data.matches??0;$('resultAvatar').textContent=(data.gameName||v)[0].toUpperCase();result.hidden=false;msg.textContent=''}catch(err){result.hidden=true;msg.textContent='Impossible de récupérer ce joueur pour le moment.'}})}

/* Maps interactives VALOHUB */
const MAPS={
 Ascent:{image:'https://valorant-hq.com/wp-content/uploads/2020/06/Ascend-2.png',sites:'A / B',desc:'Carte ouverte centrée sur le contrôle de Mid. Les portes des sites peuvent être fermées et modifient les rotations.'},
 Haven:{image:'https://valorant-hq.com/wp-content/uploads/2020/06/HavenCAlls-985x1024.png',sites:'A / B / C',desc:'Carte à trois sites : la maîtrise des rotations et des callouts est essentielle pour défendre efficacement.'},
 Bind:{image:'https://book.gamess.co.kr/uploads/images/gallery/2024-12/4iTxrAG6ujGkgkWW-image.png',sites:'A / B',desc:'Deux sites sans Mid et deux téléporteurs à sens unique. Écoute les TP pour anticiper les rotations.'},
 Sunset:{image:'https://cdn.sanity.io/images/ccckgjf9/production/749538ab4bef01bbe72ee72634fd0e0f20107799-1277x1174.png?auto=format&fit=scale&max-h=1080&max-w=1920&q=50',sites:'A / B',desc:'Le contrôle de Mid permet de connecter rapidement les deux sites. Attention aux accès A Main et B Market.'}
};

const style=document.createElement('style');
style.textContent=`.valohub-map-modal{position:fixed;inset:0;z-index:9999;background:rgba(7,3,12,.88);backdrop-filter:blur(12px);display:grid;place-items:center;padding:24px}.valohub-map-window{width:min(1100px,96vw);max-height:94vh;overflow:auto;background:linear-gradient(145deg,#24102d,#100713);border:1px solid #74315f;border-radius:16px;box-shadow:0 30px 100px #000;position:relative}.valohub-map-head{display:flex;justify-content:space-between;align-items:center;padding:18px 22px;border-bottom:1px solid #4b2948;position:sticky;top:0;background:#160b1eeF;backdrop-filter:blur(12px);z-index:2}.valohub-map-head small{display:block;color:#ff6682;font-weight:900;letter-spacing:3px;font-size:9px}.valohub-map-head h2{margin:3px 0 0;font-size:28px}.valohub-map-close{border:1px solid #67305b;background:#29142f;color:#fff;border-radius:8px;width:42px;height:42px;font-size:22px;cursor:pointer}.valohub-map-close:hover{background:linear-gradient(135deg,#ff365f,#8b3dff)}.valohub-map-content{padding:22px}.valohub-map-image-wrap{background:#09050d;border:1px solid #4f2850;border-radius:12px;padding:12px;overflow:auto;text-align:center}.valohub-map-image{max-width:100%;height:auto;display:block;margin:auto;border-radius:7px;cursor:zoom-in}.valohub-map-info{display:grid;grid-template-columns:1fr 180px;gap:14px;margin-top:14px}.valohub-map-info article{cursor:default;margin:0}.valohub-map-info article:hover{transform:none;box-shadow:none}.valohub-map-info b{color:#ff7189;font-size:10px;letter-spacing:2px}.valohub-map-info p{margin:8px 0 0;color:#bda9bf}.valohub-map-sites{display:flex;align-items:center;justify-content:center;flex-direction:column;background:#211027;border:1px solid #4a2849;border-radius:8px;color:#d9c2dc}.valohub-map-sites strong{font-size:22px;color:#fff}.valohub-map-hint{font-size:10px;color:#8f7591;margin-top:10px;text-align:center}@media(max-width:700px){.valohub-map-info{grid-template-columns:1fr}.valohub-map-content{padding:12px}.valohub-map-head h2{font-size:22px}}`;
document.head.appendChild(style);

function openMap(name){const map=MAPS[name];if(!map)return;const old=document.querySelector('.valohub-map-modal');if(old)old.remove();const modal=document.createElement('div');modal.className='valohub-map-modal';modal.innerHTML=`<div class="valohub-map-window" role="dialog" aria-modal="true" aria-label="Carte ${name}"><div class="valohub-map-head"><div><small>MAP // INTERACTIVE</small><h2>${name}</h2></div><button class="valohub-map-close" aria-label="Fermer">×</button></div><div class="valohub-map-content"><div class="valohub-map-image-wrap"><img class="valohub-map-image" src="${map.image}" alt="Carte détaillée ${name} avec callouts" loading="eager"><div class="valohub-map-hint">Clique sur l'image pour l'agrandir • Échap pour fermer</div></div><div class="valohub-map-info"><article><b>APERÇU TACTIQUE</b><p>${map.desc}</p></article><div class="valohub-map-sites"><small>SITES</small><strong>${map.sites}</strong></div></div></div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.valohub-map-close').onclick=close;modal.addEventListener('click',e=>{if(e.target===modal)close()});document.addEventListener('keydown',function esc(e){if(e.key==='Escape'){close();document.removeEventListener('keydown',esc)}});const img=modal.querySelector('.valohub-map-image');img.onclick=()=>{img.style.maxWidth=img.style.maxWidth==='none'?'100%':'none';img.style.cursor=img.style.maxWidth==='none'?'zoom-out':'zoom-in'};}

document.querySelectorAll('.map-card').forEach(card=>{card.addEventListener('click',()=>openMap(card.dataset.map))});

/* Ancien comportement des détails conservé si présent */
document.querySelectorAll('.weapon-card').forEach(card=>card.addEventListener('click',()=>{const detail=$('weaponDetail');if(!detail)return;const w=card.dataset.weapon;const info={Vandal:['VANDAL','Rifle polyvalent : 25 balles, dégâts élevés et très efficace à longue distance.','2900'],Phantom:['PHANTOM','Rifle précis et silencieux avec excellente stabilité à moyenne distance.','2900'],Operator:['OPERATOR','Sniper très puissant capable d'éliminer sur un tir au corps ou à la tête.','4700'],Sheriff:['SHERIFF','Pistolet lourd puissant, particulièrement efficace avec des tirs précis.','800']}[w];if(info){$('weaponTitle').textContent=info[0];$('weaponInfo').textContent=info[1];$('weaponPrice').textContent=info[2];detail.hidden=false}}));
